[build]
builder = "dockerFile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "never"
startCommand = "/app/start.sh"

[[services]]
name = "sicap-kibana"

[services.source]
type = "git"

[services.variables]
NODE_ENV = "production"
PORT = "5601"

[services.healthcheck]
path = "/health"
port = 8080

[services.resources]
memory = "3Gi"
cpu = "1"

# Railway will automatically expose port 5601 for Kibana
[services.networking]
port = 5601 